backend:
  name: github
  repo: 'SEU-NOME-DO-GITHUB/NOME-DO-REPOSITORIO'
  branch: 'main'
  auth_type: 'pkce'
  app_id: 'O_SEU_CLIENT_ID_DO_GITHUB'

media_folder: 'images'
public_folder: '/images'

collections:
  - name: 'caderno'
    label: 'O Caderno (Artigos)'
    folder: 'content/caderno'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Título do Artigo', name: 'title', widget: 'string' }
      - { label: 'Data de Publicação', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', date_format: 'DD/MM/YYYY', time_format: false }
      - { label: 'Imagem de Capa', name: 'image', widget: 'image', required: false }
      - { label: 'Categoria Principal', name: 'categoria', widget: 'string', default: 'Reflexão' }
      - { label: 'Tags / Palavras-chave', name: 'tags', widget: 'list', required: false }
      - { label: 'Excerto / Resumo', name: 'resumo', widget: 'text', required: false }
      - { label: 'Guardar como Rascunho?', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Conteúdo do Artigo', name: 'body', widget: 'markdown' }
